[program:bazel-remote]
command=/usr/local/bin/bazel-remote
    --dir=/var/cache/bazel-remote
    --max_size=%(ENV_BAZEL_REMOTE_MAX_SIZE_GB)s
    --port=8080
    --grpc_port=9092
autostart=true
autorestart=true
priority=10
stdout_logfile=/var/log/supervisor/bazel-remote.log
stdout_logfile_maxbytes=5MB
stderr_logfile=/var/log/supervisor/bazel-remote.log
stderr_logfile_maxbytes=5MB
