[program:nexus-init]
command=/opt/score-cache/nexus-init.sh
autostart=true
autorestart=false
startsecs=0
priority=40
stdout_logfile=/var/log/supervisor/nexus-init.log
stdout_logfile_maxbytes=5MB
stderr_logfile=/var/log/supervisor/nexus-init.log
stderr_logfile_maxbytes=5MB
