[program:nexus]
command=/opt/sonatype/nexus/bin/nexus run
directory=/opt/sonatype/nexus
user=nexus
autostart=true
autorestart=true
priority=20
environment=JAVA_HOME="",INSTALL4J_ADD_VM_PARAMS="-Xms1024m -Xmx1024m -XX:MaxDirectMemorySize=2703m -Djava.util.prefs.userRoot=/nexus-data/javaprefs"
stdout_logfile=/var/log/supervisor/nexus.log
stdout_logfile_maxbytes=10MB
stderr_logfile=/var/log/supervisor/nexus.log
stderr_logfile_maxbytes=10MB
