[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
priority=30
stdout_logfile=/var/log/supervisor/nginx.log
stdout_logfile_maxbytes=5MB
stderr_logfile=/var/log/supervisor/nginx.log
stderr_logfile_maxbytes=5MB
